version: 0.2

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
    - aws cloudformation package --template-file template.yml 
                                  --s3-bucket s3buildbucketname
                                  --output-template-file newtemplate.yml
    - aws cloudformation deploy --stack-name LambdaName
                                --capabilities CAPABILITY_IAM
                                --template-file newtemplate.yml
                                --role-arn arn:aws:iam::850837110171:role/CloudFormationServiceRole
  post_build:
    commands:
      - echo Build completed