# required
AWSTemplateFormatVersion : '2010-09-09'
# required
Transform: AWS::Serverless-2016-10-31
# short description
Description: CloudFormation Stack for lambda function
# define the resources (you can define more than one)
Resources:
  # name of the resource
  LambdaName:
    # required
    Type: AWS::Serverless::Function
    # main properties
    Properties:
      # edit based on your needs
      Handler: index.handler
      Runtime: nodejs18.x
      CodeUri: src/
# Creates an alias named "live" for the function, and automatically publishes when you update the function.
      AutoPublishAlias: live
      DeploymentPreference:
# Specifies the deployment configuration
          Type: AllAtOnce
      # default is 3, this is 15 minutes
      Timeout: 900 
      # memory allocated, maximum is 10240
      MemorySize: 5120